"""
Track Map Auto-Generator
==========================
Generates a skeleton track map markdown file from GPS trace and braking zone data.
Provides generic turn names ("Turn 1", "Turn 2", etc.) positioned at the correct
track percentages, ready for the user to rename with official corner names.

Usage:
    from tenths.track_map_generator import generate_skeleton_track_map
    content = generate_skeleton_track_map(data, session_info)
"""

import os

from tenths.config import is_metric
from tenths.units import to_display_units


def generate_skeleton_track_map(data, session_info):
    """Generate a skeleton track map markdown file from analysis data.

    Args:
        data: dict from analyzer.analyze() — needs braking_zones, gps_trace, track_length_m
        session_info: dict from parse_session_info() or data['session_info']

    Returns:
        String containing the complete markdown track map file content.
    """
    # The analyzer works in SI; the generated map shows display units.
    data = to_display_units(data, metric=is_metric())

    # Track metadata
    track_name = session_info.get('track_display_name', 'Unknown Track')
    track_config = session_info.get('track_config_name', '')
    track_display = f"{track_name} — {track_config}" if track_config else track_name
    track_country = session_info.get('track_country', '')
    track_length_m = data.get('track_length_m', 0)
    track_length_mi = track_length_m / 1609.34 if track_length_m > 0 else 0
    track_length_km = track_length_m / 1000 if track_length_m > 0 else 0
    num_turns = session_info.get('track_num_turns', 0)
    track_id = session_info.get('track_id', 0)

    braking_zones = data.get('braking_zones', [])
    gps_trace = data.get('gps_trace', [])

    # Car info for context
    car_name = session_info.get('car_screen_name', 'Unknown Car')

    lines = []

    # Header
    lines.append(f"# {track_display}")
    lines.append("")
    lines.append("<!-- Auto-generated by Tenths. Edit turn names manually. -->")
    lines.append("")

    # Track Info
    lines.append("## Track Info")
    if track_length_m > 0:
        lines.append(f"- **Length:** {track_length_mi:.2f} mi / {track_length_km:.2f} km")
    if num_turns > 0:
        lines.append(f"- **Turns:** {num_turns}")
    if track_country:
        lines.append(f"- **Country:** {track_country}")
    if track_id:
        lines.append(f"- **iRacing Track ID:** {track_id}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Turn Map table
    lines.append("## Turn Map — Telemetry % to Turn Number")
    lines.append("")
    lines.append("| Track % | Turn | Name | Direction | Description |")
    lines.append("|---|---|---|---|---|")

    for i, zone in enumerate(braking_zones, 1):
        pct = zone['pct']
        entry_mph = zone['entry_mph']
        min_mph = zone['min_mph']

        # Estimate percentage range (braking zone spans a few percent)
        pct_start = int(zone.get('entry_pct', pct) - 1)
        pct_end = int(pct + 2)

        # Generic turn name
        turn_label = f"T{i}" if len(braking_zones) <= 12 else f"T{i:02d}"

        desc = f"Braking zone ({entry_mph:.0f}→{min_mph:.0f}mph)"

        lines.append(f"| ~{pct_start}-{pct_end}% | **{turn_label}** | — | — | {desc} |")

    lines.append("")
    lines.append("---")
    lines.append("")

    # Braking Zones with GPS
    lines.append("## Telemetry Braking Zones → Turn Mapping")
    lines.append("")
    lines.append(f"Based on telemetry data from {car_name}:")
    lines.append("")
    lines.append("| Telemetry % | Dist | GPS Lat | GPS Lon | Entry | Min | Turn |")
    lines.append("|---|---|---|---|---|---|---|")

    for i, zone in enumerate(braking_zones, 1):
        pct = zone.get('entry_pct', zone['pct'])
        dist_m = zone.get('dist_m', 0)
        lat = zone.get('lat', 0)
        lon = zone.get('lon', 0)
        entry_mph = zone['entry_mph']
        min_mph = zone['min_mph']
        turn_label = f"T{i}" if len(braking_zones) <= 12 else f"T{i:02d}"

        lat_str = f"{lat:.6f}" if lat != 0 else "—"
        lon_str = f"{lon:.6f}" if lon != 0 else "—"
        dist_str = f"{dist_m:.0f}m" if dist_m > 0 else "—"

        lines.append(f"| {pct:.1f}% | {dist_str} | {lat_str} | {lon_str} | {entry_mph:.0f} mph | {min_mph:.0f} mph | **{turn_label}** |")

    lines.append("")
    lines.append("---")
    lines.append("")

    # Performance History placeholder
    lines.append(f"## Performance History ({car_name})")
    lines.append("")
    lines.append("| Date | Session | Best Lap | Cleanest ABS | Notes |")
    lines.append("|---|---|---|---|---|")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Coaching Notes placeholder
    lines.append("## Coaching Notes")
    lines.append("")
    lines.append("_Auto-generated track map. Update turn names from the iRacing track map overlay._")
    lines.append("")

    return "\n".join(lines)


def write_skeleton_track_map(content, track_slug, tracks_dir=None):
    """Write the skeleton track map to a file.

    Args:
        content: markdown string from generate_skeleton_track_map()
        track_slug: filename slug (e.g., 'daytona_rallycross_short')
        tracks_dir: directory to write to. Defaults to config.USER_TRACKS_DIR,
                    a per-user location outside the install directory.

    Returns:
        Path to the written file, or None if the file already exists or the
        directory cannot be created.

    The default deliberately does NOT use the bundled `tracks` directory. That
    path is derived from __file__, which in a frozen build lands inside the
    install folder — overwritten on upgrade and removed on uninstall, so
    generated maps were silently lost. It also made the write target
    unredirectable, so the test suite wrote into the repository.
    """
    if tracks_dir is None:
        # Read at call time so tests and overrides can redirect it.
        from tenths.config import USER_TRACKS_DIR
        tracks_dir = USER_TRACKS_DIR

    filepath = os.path.join(tracks_dir, f"{track_slug}.md")

    try:
        os.makedirs(tracks_dir, exist_ok=True)

        # Don't overwrite existing track maps — a hand-edited map must survive
        if os.path.exists(filepath):
            return None

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
    except OSError:
        # A generated map is a convenience, never worth failing a session over.
        return None

    return filepath
