"""
Tests for automatic track map generation.
"""

import os
import tempfile

import pytest

from tenths.track_map_generator import generate_skeleton_track_map, write_skeleton_track_map


class TestSkeletonGeneration:
    """Test that skeleton track maps are generated correctly."""

    def _mock_data(self):
        return {
            'track_length_m': 2945,
            'braking_zones': [
                {'pct': 6.0, 'entry_pct': 5.0, 'entry_mph': 116, 'min_mph': 75, 'dist_m': 150, 'lat': -36.518, 'lon': 146.087},
                {'pct': 19.3, 'entry_pct': 18.5, 'entry_mph': 93, 'min_mph': 61, 'dist_m': 541, 'lat': -36.516, 'lon': 146.084},
                {'pct': 46.9, 'entry_pct': 46.4, 'entry_mph': 71, 'min_mph': 57, 'dist_m': 1366, 'lat': -36.515, 'lon': 146.089},
            ],
            'gps_trace': [{'pct': i * 0.5, 'lat': -36.518, 'lon': 146.087} for i in range(200)],
        }

    def _mock_session_info(self):
        return {
            'track_display_name': 'Test Raceway',
            'track_config_name': 'Full Course',
            'track_country': 'Australia',
            'track_num_turns': 12,
            'track_id': 999,
            'car_screen_name': 'BMW M2 CS Racing',
        }

    def test_generates_valid_markdown(self):
        content = generate_skeleton_track_map(self._mock_data(), self._mock_session_info())
        assert '# Test Raceway — Full Course' in content
        assert '<!-- Auto-generated by Tenths' in content
        assert '## Turn Map' in content

    def test_contains_all_braking_zones(self):
        content = generate_skeleton_track_map(self._mock_data(), self._mock_session_info())
        assert '**T1**' in content
        assert '**T2**' in content
        assert '**T3**' in content

    def test_contains_track_info(self):
        content = generate_skeleton_track_map(self._mock_data(), self._mock_session_info())
        assert 'Australia' in content
        assert '12' in content  # num turns
        assert '999' in content  # track ID

    def test_contains_gps_coordinates(self):
        content = generate_skeleton_track_map(self._mock_data(), self._mock_session_info())
        assert '-36.518' in content
        assert '146.087' in content

    def test_contains_speed_data(self):
        content = generate_skeleton_track_map(self._mock_data(), self._mock_session_info())
        assert '116 mph' in content  # entry speed
        assert '75 mph' in content   # min speed

    def test_empty_braking_zones(self):
        """Should still generate a valid file with no turn rows."""
        data = self._mock_data()
        data['braking_zones'] = []
        content = generate_skeleton_track_map(data, self._mock_session_info())
        assert '# Test Raceway' in content
        assert '## Turn Map' in content


class TestWriteSkeletonFile:
    """Test file writing behavior."""

    def test_creates_new_file(self):
        data = {
            'track_length_m': 1000,
            'braking_zones': [{'pct': 50, 'entry_pct': 49, 'entry_mph': 80, 'min_mph': 40, 'dist_m': 500, 'lat': 0, 'lon': 0}],
            'gps_trace': [],
        }
        content = generate_skeleton_track_map(data, {'track_display_name': 'Test', 'car_screen_name': 'Car'})

        with tempfile.TemporaryDirectory() as tmpdir:
            path = write_skeleton_track_map(content, 'test_track', tmpdir)
            assert path is not None
            assert os.path.exists(path)
            assert path.endswith('test_track.md')

    def test_does_not_overwrite_existing(self):
        """Should NOT overwrite an existing track map file."""
        with tempfile.TemporaryDirectory() as tmpdir:
            filepath = os.path.join(tmpdir, 'existing_track.md')
            with open(filepath, 'w') as f:
                f.write("# Existing content\n")

            result = write_skeleton_track_map("new content", 'existing_track', tmpdir)
            assert result is None  # did not write

            with open(filepath, 'r') as f:
                assert f.read() == "# Existing content\n"  # unchanged


class TestIntegrationWithRealData:
    """Test with real analyzed session data."""

    def test_winton_skeleton_matches_zones(self, winton_race_data):
        """Generate a skeleton for Winton and verify zone count matches."""
        si = winton_race_data.get('session_info', {})
        content = generate_skeleton_track_map(winton_race_data, si)
        # Winton has 5 braking zones
        assert content.count('**T') >= 5
        assert 'Winton' in content

    def test_midohio_skeleton_has_gps(self, midohio_practice_data):
        """Mid-Ohio skeleton should include GPS coordinates."""
        si = midohio_practice_data.get('session_info', {})
        content = generate_skeleton_track_map(midohio_practice_data, si)
        assert 'Mid-Ohio' in content or 'midohio' in content.lower()
        # Should have lat/lon for braking zones
        assert '40.6' in content  # Mid-Ohio latitude range
