"""
Tests for automatic track map generation.
"""

import os
import tempfile

import pytest

from tenths.track_map_generator import generate_skeleton_track_map, write_skeleton_track_map


class TestSkeletonGeneration:
    """Test that skeleton track maps are generated correctly."""

    def _mock_data(self):
        return {
            'track_length_m': 2945,
            'braking_zones': [
                {'pct': 6.0, 'entry_pct': 5.0, 'entry_mph': 116, 'min_mph': 75, 'dist_m': 150, 'lat': -36.518, 'lon': 146.087},
                {'pct': 19.3, 'entry_pct': 18.5, 'entry_mph': 93, 'min_mph': 61, 'dist_m': 541, 'lat': -36.516, 'lon': 146.084},
                {'pct': 46.9, 'entry_pct': 46.4, 'entry_mph': 71, 'min_mph': 57, 'dist_m': 1366, 'lat': -36.515, 'lon': 146.089},
            ],
            'gps_trace': [{'pct': i * 0.5, 'lat': -36.518, 'lon': 146.087} for i in range(200)],
        }

    def _mock_session_info(self):
        return {
            'track_display_name': 'Test Raceway',
            'track_config_name': 'Full Course',
            'track_country': 'Australia',
            'track_num_turns': 12,
            'track_id': 999,
            'car_screen_name': 'BMW M2 CS Racing',
        }

    def test_generates_valid_markdown(self):
        content = generate_skeleton_track_map(self._mock_data(), self._mock_session_info())
        assert '# Test Raceway — Full Course' in content
        assert '<!-- Auto-generated by Tenths' in content
        assert '## Turn Map' in content

    def test_contains_all_braking_zones(self):
        content = generate_skeleton_track_map(self._mock_data(), self._mock_session_info())
        assert '**T1**' in content
        assert '**T2**' in content
        assert '**T3**' in content

    def test_contains_track_info(self):
        content = generate_skeleton_track_map(self._mock_data(), self._mock_session_info())
        assert 'Australia' in content
        assert '12' in content  # num turns
        assert '999' in content  # track ID

    def test_contains_gps_coordinates(self):
        content = generate_skeleton_track_map(self._mock_data(), self._mock_session_info())
        assert '-36.518' in content
        assert '146.087' in content

    def test_contains_speed_data(self):
        content = generate_skeleton_track_map(self._mock_data(), self._mock_session_info())
        assert '116 mph' in content  # entry speed
        assert '75 mph' in content   # min speed

    def test_empty_braking_zones(self):
        """Should still generate a valid file with no turn rows."""
        data = self._mock_data()
        data['braking_zones'] = []
        content = generate_skeleton_track_map(data, self._mock_session_info())
        assert '# Test Raceway' in content
        assert '## Turn Map' in content


class TestWriteSkeletonFile:
    """Test file writing behavior."""

    def test_creates_new_file(self):
        data = {
            'track_length_m': 1000,
            'braking_zones': [{'pct': 50, 'entry_pct': 49, 'entry_mph': 80, 'min_mph': 40, 'dist_m': 500, 'lat': 0, 'lon': 0}],
            'gps_trace': [],
        }
        content = generate_skeleton_track_map(data, {'track_display_name': 'Test', 'car_screen_name': 'Car'})

        with tempfile.TemporaryDirectory() as tmpdir:
            path = write_skeleton_track_map(content, 'test_track', tmpdir)
            assert path is not None
            assert os.path.exists(path)
            assert path.endswith('test_track.md')

    def test_does_not_overwrite_existing(self):
        """Should NOT overwrite an existing track map file."""
        with tempfile.TemporaryDirectory() as tmpdir:
            filepath = os.path.join(tmpdir, 'existing_track.md')
            with open(filepath, 'w') as f:
                f.write("# Existing content\n")

            result = write_skeleton_track_map("new content", 'existing_track', tmpdir)
            assert result is None  # did not write

            with open(filepath, 'r') as f:
                assert f.read() == "# Existing content\n"  # unchanged


class TestIntegrationWithRealData:
    """Test with real analyzed session data."""

    def test_winton_skeleton_matches_zones(self, winton_race_data):
        """Generate a skeleton for Winton and verify zone count matches."""
        si = winton_race_data.get('session_info', {})
        content = generate_skeleton_track_map(winton_race_data, si)
        # Winton has 5 braking zones
        assert content.count('**T') >= 5
        assert 'Winton' in content

    def test_midohio_skeleton_has_gps(self, midohio_practice_data):
        """Mid-Ohio skeleton should include GPS coordinates."""
        si = midohio_practice_data.get('session_info', {})
        content = generate_skeleton_track_map(midohio_practice_data, si)
        assert 'Mid-Ohio' in content or 'midohio' in content.lower()
        # Should have lat/lon for braking zones
        assert '40.6' in content  # Mid-Ohio latitude range


class TestWriteTargetIsUserWritable:
    """RR-023: generated maps must not be written into the install/repo directory.

    The original default derived its target from __file__, which meant:
      - the test suite wrote `tracks/test_track.md` into the repository
      - a frozen build wrote into `_internal/tracks/`, which the installer
        overwrites on upgrade and removes on uninstall, silently destroying
        the user's generated maps
      - TENTHS_TRACKS_DIR overrode reads but not writes
    """

    def test_default_target_is_config_user_tracks_dir(self, tmp_path, monkeypatch):
        """With no explicit dir, the writer must use config.USER_TRACKS_DIR."""
        from tenths import config
        target = tmp_path / "user_tracks"
        monkeypatch.setattr(config, "USER_TRACKS_DIR", str(target))

        written = write_skeleton_track_map("# Test\n", "some_track")

        assert written is not None, "expected a file to be written"
        assert os.path.isfile(written)
        # Must be inside the redirected dir, proving config is honoured
        assert os.path.normcase(str(target)) in os.path.normcase(written)

    def test_default_target_is_not_the_bundled_tracks_dir(self):
        """The write target must never be the package's read-only tracks dir."""
        from tenths import config
        import tenths.track_map_generator as tmg

        bundled = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(tmg.__file__))), "tracks")

        assert os.path.normcase(config.USER_TRACKS_DIR) != os.path.normcase(bundled), (
            "USER_TRACKS_DIR must not be the bundled tracks directory — in a frozen "
            "build that lives inside the install folder and is wiped on upgrade")

    def test_default_target_lives_under_app_data(self):
        """Generated maps belong in per-user app data, not the program folder.

        Asserts the *configured* default, recomputed here rather than read from
        config, because the autouse test guard redirects USER_TRACKS_DIR to a
        temp dir for isolation.
        """
        from tenths import config
        expected = os.path.join(config.APP_DATA_DIR, "tracks")
        actual = os.environ.get('TENTHS_USER_TRACKS_DIR', expected)
        assert os.path.normcase(config.APP_DATA_DIR) in os.path.normcase(actual)

    def test_explicit_dir_still_honoured(self, tmp_path):
        """An explicit tracks_dir argument overrides the default."""
        written = write_skeleton_track_map("# Test\n", "explicit_track",
                                          tracks_dir=str(tmp_path))
        assert written == os.path.join(str(tmp_path), "explicit_track.md")
        assert os.path.isfile(written)

    def test_existing_map_is_never_overwritten(self, tmp_path):
        """A hand-edited map must survive regeneration."""
        existing = tmp_path / "keepme.md"
        existing.write_text("# Hand edited\n", encoding="utf-8")

        result = write_skeleton_track_map("# Generated\n", "keepme",
                                         tracks_dir=str(tmp_path))

        assert result is None, "should refuse to overwrite"
        assert existing.read_text(encoding="utf-8") == "# Hand edited\n"

    def test_unwritable_target_degrades_gracefully(self, monkeypatch):
        """A generated map is a convenience; it must never fail a session."""
        import tenths.track_map_generator as tmg

        def boom(*args, **kwargs):
            raise OSError("read-only filesystem")

        monkeypatch.setattr(tmg.os, "makedirs", boom)

        # Must return None rather than propagating
        assert write_skeleton_track_map("# Test\n", "t", tracks_dir="/nope") is None


class TestGeneratedMapIsReadable:
    """A map written to the user dir must be found by the loader."""

    def test_user_dir_is_in_the_read_search_path(self):
        from tenths import config
        from tenths.track_map import TRACK_MAPS_DIRS

        normalized = [os.path.normcase(d) for d in TRACK_MAPS_DIRS if d]
        assert os.path.normcase(config.USER_TRACKS_DIR) in normalized, (
            "USER_TRACKS_DIR must be searched on read, or generated maps are "
            "written somewhere the loader never looks")

    def test_user_dir_is_searched_before_bundled_maps(self):
        """A user's own map for a track should win over a shipped one."""
        from tenths import config
        from tenths.track_map import TRACK_MAPS_DIRS

        normalized = [os.path.normcase(d) for d in TRACK_MAPS_DIRS if d]
        user_idx = normalized.index(os.path.normcase(config.USER_TRACKS_DIR))

        bundled = [i for i, d in enumerate(normalized)
                   if d.endswith(os.path.normcase(os.sep + "tracks"))
                   and i != user_idx]
        assert bundled, "expected at least one bundled tracks dir in the search path"
        assert user_idx < min(bundled), (
            "user-generated maps must be searched before bundled maps")


class TestUserDirDoesNotBreakBundledMaps:
    """User-first ordering must not stop curated bundled maps from loading."""

    def test_bundled_map_still_loads_when_user_dir_is_empty(self, tmp_path, monkeypatch):
        """An empty user dir must contribute no candidates and fall through."""
        import tenths.track_map as tm

        bundled = tmp_path / "bundled"
        bundled.mkdir()
        (bundled / "winton_national.md").write_text(
            "# Winton National\n\n## Turn Map\n\n"
            "| Track % | Turn | Name | Direction | Description |\n"
            "|---|---|---|---|---|\n"
            "| ~5-7% | **T1** | Bundled Turn | Left | test |\n",
            encoding="utf-8")

        empty_user = tmp_path / "user"
        empty_user.mkdir()

        monkeypatch.setattr(tm, "TRACK_MAPS_DIRS",
                            [str(empty_user), str(bundled)])

        found = tm._load_from_md_file("winton_national")
        assert found, "bundled map must still be found when the user dir is empty"

    def test_user_map_wins_when_both_exist(self, tmp_path, monkeypatch):
        """A user's own map for the same track takes precedence.

        This is the deliberate trade-off of user-first ordering: an edited map
        wins. The cost is that a stale generic skeleton also wins until the user
        deletes it — see POST_MVP.md for the marker-based resolution.
        """
        import tenths.track_map as tm

        table = ("\n\n## Turn Map\n\n"
                 "| Track % | Turn | Name | Direction | Description |\n"
                 "|---|---|---|---|---|\n"
                 "| ~5-7% | **T1** | {name} | Left | test |\n")

        bundled = tmp_path / "bundled"
        bundled.mkdir()
        (bundled / "sometrack.md").write_text("# Bundled" + table.format(name="Bundled Turn"),
                                             encoding="utf-8")

        user = tmp_path / "user"
        user.mkdir()
        (user / "sometrack.md").write_text("# User" + table.format(name="User Turn"),
                                          encoding="utf-8")

        monkeypatch.setattr(tm, "TRACK_MAPS_DIRS", [str(user), str(bundled)])

        result = tm._load_from_md_file("sometrack")
        assert result, "expected a map to load"
        names = str(result)
        assert "User Turn" in names, f"user map should win, got: {names}"
